# https://github.com/subosito/flutter-action
name: Flutter_Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test --coverage
      - run: flutter build apk
      - run: flutter build appbundle



